[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ratatai"
version = "0.1.0"
dependencies = [
    "mypy",
    "better_exceptions",
    "pre-commit"
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
