[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ratatai"
version = "0.1.0"
# Dependencies should be installed by the user of the library.
dependencies = [
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
